include:
  - ../db-entity/compose.yaml

services:
  api-entity:
    build: .
    container_name: api-entity
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/healthcheck" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - net-entity
    depends_on:
      - db-entity
networks:
  net-entity:
    driver: bridge
