import { IEndpointTypeControllerUpdateEndpointTypeOutputError } from './IEndpointTypeControllerUpdateEndpointTypeOutputError';
import { IEndpointTypeControllerUpdateEndpointTypeOutputSuccess } from './IEndpointTypeControllerUpdateEndpointTypeOutputSuccess';

export type IEndpointTypeControllerUpdateEndpointTypeOutput =
  | IEndpointTypeControllerUpdateEndpointTypeOutputSuccess
  | IEndpointTypeControllerUpdateEndpointTypeOutputError;
