import { IFrameworkTypeControllerCreateFrameworkTypeOutputError } from './IFrameworkTypeControllerCreateFrameworkTypeOutputError';
import { IFrameworkTypeControllerCreateFrameworkTypeOutputSuccess } from './IFrameworkTypeControllerCreateFrameworkTypeOutputSuccess';

export type IFrameworkTypeControllerCreateFrameworkTypeOutput =
  | IFrameworkTypeControllerCreateFrameworkTypeOutputSuccess
  | IFrameworkTypeControllerCreateFrameworkTypeOutputError;
