import { IFrameworkTypeControllerUpdateFrameworkTypeOutputError } from './IFrameworkTypeControllerUpdateFrameworkTypeOutputError';
import { IFrameworkTypeControllerUpdateFrameworkTypeOutputSuccess } from './IFrameworkTypeControllerUpdateFrameworkTypeOutputSuccess';

export type IFrameworkTypeControllerUpdateFrameworkTypeOutput =
  | IFrameworkTypeControllerUpdateFrameworkTypeOutputSuccess
  | IFrameworkTypeControllerUpdateFrameworkTypeOutputError;
