import { IFrameworkTypeControllerReadFrameworkTypeOutputError } from './IFrameworkTypeControllerReadFrameworkTypeOutputError';
import { IFrameworkTypeControllerReadFrameworkTypeOutputSuccess } from './IFrameworkTypeControllerReadFrameworkTypeOutputSuccess';

export type IFrameworkTypeControllerReadFrameworkTypeOutput =
  | IFrameworkTypeControllerReadFrameworkTypeOutputSuccess
  | IFrameworkTypeControllerReadFrameworkTypeOutputError;
