import { IResourceTypeControllerUpdateResourceTypeOutputError } from './IResourceTypeControllerUpdateResourceTypeOutputError';
import { IResourceTypeControllerUpdateResourceTypeOutputSuccess } from './IResourceTypeControllerUpdateResourceTypeOutputSuccess';

export type IResourceTypeControllerUpdateResourceTypeOutput =
  | IResourceTypeControllerUpdateResourceTypeOutputSuccess
  | IResourceTypeControllerUpdateResourceTypeOutputError;
